; pokedex ids
; indexes for:
; - BaseStats (see data/pokemon/base_stats.asm)
; - MonPartyData (see data/pokemon/menu_icons.asm)
; - MonsterPalettes (see data/pokemon/palettes.asm)
	const_def 1
	const DEX_BULBASAUR  ; 1
	const DEX_IVYSAUR    ; 2
	const DEX_VENUSAUR   ; 3
	const DEX_CHARMANDER ; 4
	const DEX_CHARMELEON ; 5
	const DEX_CHARIZARD  ; 6
	const DEX_SQUIRTLE   ; 7
	const DEX_WARTORTLE  ; 8
	const DEX_BLASTOISE  ; 9
	const DEX_CATERPIE   ; 10
	const DEX_METAPOD    ; 11
	const DEX_BUTTERFREE ; 12
	const DEX_WEEDLE     ; 13
	const DEX_KAKUNA     ; 14
	const DEX_BEEDRILL   ; 15
	const DEX_PIDGEY     ; 16
	const DEX_PIDGEOTTO  ; 17
	const DEX_PIDGEOT    ; 18
	const DEX_RATTATA    ; 19
	const DEX_RATICATE   ; 20
	const DEX_SPEAROW    ; 21
	const DEX_FEAROW     ; 22
	const DEX_EKANS      ; 23
	const DEX_ARBOK      ; 24
	const DEX_PICHU      ; 25
	const DEX_PIKACHU    ; 26
	const DEX_RAICHU     ; 27
	const DEX_SANDSHREW  ; 28
	const DEX_SANDSLASH  ; 29
	const DEX_NIDORAN_F  ; 30
	const DEX_NIDORINA   ; 31
	const DEX_NIDOQUEEN  ; 32
	const DEX_NIDORAN_M  ; 33
	const DEX_NIDORINO   ; 34
	const DEX_NIDOKING   ; 35
	const DEX_CLEFFA     ; 36
	const DEX_CLEFAIRY   ; 37
	const DEX_CLEFABLE   ; 38
	const DEX_VULPIX     ; 39
	const DEX_NINETALES  ; 40
	const DEX_IGGLYBUFF  ; 41
	const DEX_JIGGLYPUFF ; 42
	const DEX_WIGGLYTUFF ; 43
	const DEX_ZUBAT      ; 44
	const DEX_GOLBAT     ; 45
	const DEX_CROBAT     ; 46
	const DEX_ODDISH     ; 47
	const DEX_GLOOM      ; 48
	const DEX_VILEPLUME  ; 49
	const DEX_BELLOSSOM  ; 50
	const DEX_PARAS      ; 51
	const DEX_PARASECT   ; 52
	const DEX_VENONAT    ; 53
	const DEX_VENOMOTH   ; 54
	const DEX_DIGLETT    ; 55
	const DEX_DUGTRIO    ; 56
	const DEX_MEOWTH     ; 57
	const DEX_PERSIAN    ; 58
	const DEX_PSYDUCK    ; 59
	const DEX_GOLDUCK    ; 60
	const DEX_MANKEY     ; 61
	const DEX_PRIMEAPE   ; 62
	const DEX_ANNIHILAPE ; 63
	const DEX_GROWLITHE  ; 64
	const DEX_ARCANINE   ; 65
	const DEX_POLIWAG    ; 66
	const DEX_POLIWHIRL  ; 67
	const DEX_POLIWRATH  ; 68
	const DEX_POLITOED   ; 69
	const DEX_ABRA       ; 70
	const DEX_KADABRA    ; 71
	const DEX_ALAKAZAM   ; 72
	const DEX_MACHOP     ; 73
	const DEX_MACHOKE    ; 74
	const DEX_MACHAMP    ; 75
	const DEX_BELLSPROUT ; 76
	const DEX_WEEPINBELL ; 77
	const DEX_VICTREEBEL ; 78
	const DEX_TENTACOOL  ; 79
	const DEX_TENTACRUEL ; 80
	const DEX_GEODUDE    ; 81
	const DEX_GRAVELER   ; 82
	const DEX_GOLEM      ; 83
	const DEX_PONYTA     ; 84
	const DEX_RAPIDASH   ; 85
	const DEX_SLOWPOKE   ; 86
	const DEX_SLOWBRO    ; 87
	const DEX_SLOWKING   ; 88
	const DEX_MAGNEMITE  ; 89
	const DEX_MAGNETON   ; 90
	const DEX_MAGNEZONE  ; 91
	const DEX_FARFETCHD  ; 92
	const DEX_DODUO      ; 93
	const DEX_DODRIO     ; 94
	const DEX_SEEL       ; 95
	const DEX_DEWGONG    ; 96
	const DEX_GRIMER     ; 97
	const DEX_MUK        ; 98
	const DEX_SHELLDER   ; 99
	const DEX_CLOYSTER   ; 100
	const DEX_GASTLY     ; 101
	const DEX_HAUNTER    ; 102
	const DEX_GENGAR     ; 103
	const DEX_ONIX       ; 104
	const DEX_STEELIX    ; 105
	const DEX_DROWZEE    ; 106
	const DEX_HYPNO      ; 107
	const DEX_KRABBY     ; 108
	const DEX_KINGLER    ; 109
	const DEX_VOLTORB    ; 110
	const DEX_ELECTRODE  ; 111
	const DEX_EXEGGCUTE  ; 112
	const DEX_EXEGGUTOR  ; 113
	const DEX_CUBONE     ; 114
	const DEX_MAROWAK    ; 115
	const DEX_TYROGUE    ; 116
	const DEX_HITMONLEE  ; 117
	const DEX_HITMONCHAN ; 118
	const DEX_HITMONTOP	 ; 119
	const DEX_LICKITUNG  ; 120
	const DEX_LICKILICKY ; 121
	const DEX_KOFFING    ; 122
	const DEX_WEEZING    ; 123
	const DEX_RHYHORN    ; 124
	const DEX_RHYDON     ; 125
	const DEX_RHYPERIOR  ; 126
	const DEX_HAPPINY    ; 127
	const DEX_CHANSEY    ; 128
	const DEX_BLISSEY    ; 129
	const DEX_TANGELA    ; 130
	const DEX_TANGROWTH  ; 131
	const DEX_KANGASKHAN ; 132
	const DEX_HORSEA     ; 133
	const DEX_SEADRA     ; 134
	const DEX_KINGDRA    ; 135
	const DEX_GOLDEEN    ; 136
	const DEX_SEAKING    ; 137
	const DEX_STARYU     ; 138
	const DEX_STARMIE    ; 139
	const DEX_MIME_JR    ; 140
	const DEX_MR_MIME    ; 141
	const DEX_SCYTHER    ; 142
	const DEX_SCIZOR     ; 143
	const DEX_KLEAVOR    ; 144
	const DEX_SMOOCHUM   ; 145
	const DEX_JYNX       ; 146
	const DEX_ELEKID     ; 147
	const DEX_ELECTABUZZ ; 148
	const DEX_ELECTIVIRE ; 149
	const DEX_MAGBY      ; 150
	const DEX_MAGMAR     ; 151
	const DEX_MAGMORTAR  ; 152
	const DEX_PINSIR     ; 153
	const DEX_TAUROS     ; 154
	const DEX_MAGIKARP   ; 155
	const DEX_GYARADOS   ; 156
	const DEX_LAPRAS     ; 157
	const DEX_DITTO      ; 158
	const DEX_EEVEE      ; 159
	const DEX_VAPOREON   ; 160
	const DEX_JOLTEON    ; 161
	const DEX_FLAREON    ; 162
	const DEX_ESPEON     ; 163
	const DEX_LEAFEON    ; 164
	const DEX_GLACEON    ; 165
	const DEX_PORYGON    ; 166
	const DEX_PORYGON2   ; 167
	const DEX_PORYGONZ   ; 168
	const DEX_OMANYTE    ; 169
	const DEX_OMASTAR    ; 170
	const DEX_KABUTO     ; 171
	const DEX_KABUTOPS   ; 172
	const DEX_AERODACTYL ; 173
	const DEX_MUNCHLAX   ; 174
	const DEX_SNORLAX    ; 175
	const DEX_ARTICUNO   ; 176
	const DEX_ZAPDOS     ; 177
	const DEX_MOLTRES    ; 178
	const DEX_DRATINI    ; 179
	const DEX_DRAGONAIR  ; 180
	const DEX_DRAGONITE  ; 181
	const DEX_MEWTWO     ; 182
	const DEX_MEW        ; 183

DEF NUM_POKEMON EQU const_value - 1
